
server:
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.248.134:3306/bishe
    driver-class-name: com.mysql.jdbc.Driver
  http:
      multipart:
        max-file-size: 209715200  #用来指定服务端最大文件大小
        max-request-size: 209715200 #用来控制文件上传大小的限制
mybatis:
  type-aliases-package: com.zzu.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql